### ISSUE TITLE
(JavaFX) openjfx no fix the problem

### ISSUE THREAD

**Issue by NathanielFreeman** [Querz/mcaselector#63]
In Ubuntu19.10 (Debian like)
Java OpenJKD11 and openjfx install,
or with
OracleJDK13 and openjfx install
with
default-jre and openjfx install
with
default-jdk and openjfx install

java -jar mcaselector-1.9.3.jar

=

Exception in thread "main" java.lang.NoClassDefFoundError: javafx/beans/property/StringProperty
	at net.querz.mcaselector.Main.main(Main.java:25)

Caused by: java.lang.ClassNotFoundException: javafx.beans.property.StringProperty
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

**Comment by 0xfeeddeadbeef** [comment]
@NathanielFreeman I had same issue on Windows. The solution to issue #58 could help. I don't have access to Linux box, but probably command line can be something like this:

```
java --module-path /path/to/javafx/lib --add-modules ALL-MODULE-PATH -jar mcaselector-1.9.3.jar
```

**Comment by WillMorrison** [comment]
For future reference, I'm on a Debian-derivative with OpenJDK 11 and openjfx installed, the following command worked for me:

java --module-path /usr/share/openjfx/lib --add-modules ALL-MODULE-PATH -jar mcaselector-1.9.9.jar

**Comment by Taranchul** [comment]
@WillMorrison Thanks, that worked on my Ubuntu MATE 20.04, too.

@Querz Maybe this could be included in the Debian(/Ubuntu) part of https://github.com/Querz/mcaselector#if-you-receive-a-javafx-error ?
